"use client";

import { Brain, UtensilsCrossed, BarChart3, Dumbbell, Camera, Moon } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Personalisation",
    desc: "Your meal plan, workout plan, and daily guidance is generated by AI that knows your body type, goal, medical conditions, and lifestyle. No two users get the same plan.",
    accent: false,
  },
  {
    icon: UtensilsCrossed,
    title: "Indian Meal Plans",
    desc: "Real Indian food — dal, roti, sabzi, regional cuisines. No salads and quinoa forced on you.",
    accent: true,
  },
  {
    icon: BarChart3,
    title: "Calorie Tracker",
    desc: "Track calories and macros with a full Indian food database. Log meals in seconds.",
    accent: false,
  },
  {
    icon: Dumbbell,
    title: "Workout Plans",
    desc: "Gym, home, or outdoor. Adapts automatically for injuries, travel, and plateaus.",
    accent: true,
  },
  {
    icon: Camera,
    title: "Progress Photos",
    desc: "Before/after timeline with date stamps. See your transformation clearly over time.",
    accent: false,
  },
  {
    icon: Moon,
    title: "Fasting Intelligence",
    desc: "Ramzan, Navratri, Ekadashi, IF — with daily toggles. Never assumes, always adapts.",
    accent: true,
  },
];

export default function FeaturesSection() {
  return (
    <section
      id="features"
      style={{
        position: "relative",
        zIndex: 1,
        padding: "100px 48px",
        maxWidth: "1200px",
        margin: "0 auto",
      }}
    >
      {/* Section label */}
      <span style={{
        display: "inline-block",
        fontSize: "12px",
        fontWeight: 600,
        letterSpacing: "0.12em",
        textTransform: "uppercase",
        color: "var(--accent)",
        marginBottom: "16px",
      }}>
        Features
      </span>

      {/* Title */}
      <h2 style={{
        fontFamily: "var(--font-syne)",
        fontSize: "clamp(32px, 4vw, 52px)",
        fontWeight: 800,
        lineHeight: 1.1,
        letterSpacing: "-0.02em",
        marginBottom: "16px",
        color: "var(--text)",
      }}>
        Everything your<br />body actually needs
      </h2>

      {/* Subtitle */}
      <p style={{
        fontSize: "17px",
        color: "var(--text2)",
        fontWeight: 300,
        maxWidth: "480px",
        lineHeight: 1.7,
        marginBottom: "64px",
        fontFamily: "var(--font-dm-sans)",
      }}>
        Not a calorie counter. Not a recipe app. A complete AI fitness system that adapts to your real life.
      </p>

      {/* 3x2 Grid */}
      <div style={{
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "20px",
      }}>
        {features.map((feature) => {
          const Icon = feature.icon;
          const isAccent = feature.accent;

          return (
            <div
              key={feature.title}
              style={{
                background: isAccent
                  ? "var(--gradient)"
                  : "var(--card)",
                border: `1px solid ${isAccent ? "transparent" : "var(--border2)"}`,
                borderRadius: "20px",
                padding: "36px 32px",
                transition: "all 0.3s ease",
                cursor: "default",
                backdropFilter: "blur(12px)",
                boxShadow: isAccent
                  ? "0 8px 32px var(--accent-glow)"
                  : "none",
              }}
              onMouseEnter={e => {
                e.currentTarget.style.transform = "translateY(-4px)";
                if (!isAccent) {
                  e.currentTarget.style.borderColor = "var(--border)";
                  e.currentTarget.style.boxShadow = "0 20px 40px rgba(0,0,0,0.08)";
                } else {
                  e.currentTarget.style.boxShadow = "0 16px 48px var(--accent-glow)";
                }
              }}
              onMouseLeave={e => {
                e.currentTarget.style.transform = "translateY(0)";
                if (!isAccent) {
                  e.currentTarget.style.borderColor = "var(--border2)";
                  e.currentTarget.style.boxShadow = "none";
                } else {
                  e.currentTarget.style.boxShadow = "0 8px 32px var(--accent-glow)";
                }
              }}
            >
              {/* Icon */}
              <div style={{
                width: "48px",
                height: "48px",
                borderRadius: "12px",
                background: isAccent ? "rgba(255,255,255,0.15)" : "var(--accent-soft)",
                border: `1px solid ${isAccent ? "rgba(255,255,255,0.2)" : "var(--border)"}`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                marginBottom: "24px",
              }}>
                <Icon
                  size={22}
                  color={isAccent ? "white" : "var(--accent)"}
                  strokeWidth={1.5}
                />
              </div>

              {/* Title */}
              <h3 style={{
                fontFamily: "var(--font-syne)",
                fontSize: "18px",
                fontWeight: 700,
                marginBottom: "12px",
                color: isAccent ? "white" : "var(--text)",
              }}>
                {feature.title}
              </h3>

              {/* Desc */}
              <p style={{
                fontSize: "14px",
                color: isAccent ? "rgba(255,255,255,0.8)" : "var(--text2)",
                lineHeight: 1.7,
                fontWeight: 300,
                fontFamily: "var(--font-dm-sans)",
              }}>
                {feature.desc}
              </p>
            </div>
          );
        })}
      </div>
    </section>
  );
}